version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_krom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: krom_db
    ports:
      - "3307:3306"
    volumes:
      - ./seeds:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: krom_backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=krom_db
      - DB_PORT=3306